import logging

from agents.recommendation.recommendation_rule_engine import (
    RecommendationRuleEngine
)
from agents.recommendation.recommendation_engine import (
    RecommendationEngine
)
from agents.recommendation.knowledge_retriever import KnowledgeRetriever
from agents.recommendation.prompt_builder import PromptBuilder
from agents.recommendation.gemini_client import (
    GeminiClient,
    GeminiUnavailableError
)
from agents.recommendation.recommendation_validator import (
    RecommendationValidator
)
from agents.recommendation.recommendation_object_builder import (
    RecommendationObjectBuilder
)

logger = logging.getLogger(__name__)


class RecommendationAgent:
    """
    ==========================================================
    Recommendation Agent

    Responsibility:
        Generate one remediation recommendation per entity by
        reasoning over the Behavior Object, Risk Object,
        Integrity Object, and Operational Entity — using the
        deterministic Recommendation Engine, retrieved
        operational knowledge, and Gemini. This agent does NOT
        calculate behavior or risk; those are already produced
        by earlier agents. Every entity receives a
        recommendation, including LOW priority ones — nothing
        is ever skipped, and a Gemini outage never prevents a
        recommendation from being produced (see the fallback
        path).

    Input:
        Behavior Object, Risk Object, Integrity Object,
        Operational Entity (optional)

    Output:
        Recommendation Object

    DOES NOT
    --------
    - Detect anomalies
    - Calculate Behavior Score or Risk Score
    - Validate output correctness (that is the Integrity
      Agent's responsibility)
    ==========================================================
    """

    # =====================================================
    # INITIALIZATION
    # =====================================================

    def __init__(self, config_file="config/recommendation_rules.yaml",
                 prompt_template_file="config/prompt_template.txt"):

        logger.info("Initializing Recommendation Agent...")

        self.rule_engine = RecommendationRuleEngine(config_file)

        self.recommendation_engine = RecommendationEngine(
            self.rule_engine
        )

        self.knowledge_retriever = KnowledgeRetriever(self.rule_engine)

        self.prompt_builder = PromptBuilder(prompt_template_file)

        self.gemini_client = GeminiClient(self.rule_engine)

        self.recommendation_validator = RecommendationValidator(
            self.rule_engine
        )

        self.recommendation_object_builder = RecommendationObjectBuilder()

        validation_config = self.rule_engine.get_validation_config()

        self.max_validation_retries = validation_config.get(
            "max_retries", 1
        )

        self.total_behaviors = 0
        self.total_recommendations = 0
        self.total_generated_by_gemini = 0
        self.total_generated_by_fallback = 0

        logger.info("Recommendation Agent Ready.")

    # =====================================================
    # HEALTH CHECK
    # =====================================================

    def health_check(self):

        logger.info("Running Recommendation Agent Health Check...")

        self.rule_engine.health_check()

        logger.info("Recommendation Engine Ready.")
        logger.info("Knowledge Retriever Ready.")
        logger.info("Prompt Builder Ready.")
        logger.info("Gemini Client Ready.")
        logger.info("Recommendation Validator Ready.")
        logger.info("Recommendation Object Builder Ready.")

        logger.info("Recommendation Agent Health Check PASSED.")

    # =====================================================
    # BUILD FALLBACK CANDIDATE
    #
    # Always valid by construction — guarantees a
    # Recommendation Object is produced even with no LLM
    # connectivity at all.
    # =====================================================

    def _build_fallback_candidate(self, context):

        fallback_config = self.rule_engine.get_fallback_config()

        recommendation_by_priority = fallback_config.get(
            "recommendation_by_priority", {}
        )

        priority = context.get("priority")

        recommendation_text = recommendation_by_priority.get(
            priority,
            "Review this entity; no specific fallback recommendation "
            "configured for this priority."
        )

        return {

            "priority": priority,

            "recommendation": recommendation_text,

            "reason": fallback_config.get(
                "reason",
                "Generated by the deterministic fallback path."
            ),

            "expected_impact": context.get("expected_impact"),

            "estimated_recovery_time": context.get(
                "estimated_recovery_time"
            ),

            "confidence": fallback_config.get("confidence", 0.3),

            "automation_possible": context.get("automation_possible"),

            "human_approval_required": context.get(
                "human_approval_required"
            )

        }

    # =====================================================
    # GENERATE VIA GEMINI, WITH ONE VALIDATION RETRY
    # =====================================================

    def _generate_via_gemini(self, context, retrieved_knowledge):

        prompt = self.prompt_builder.build(context, retrieved_knowledge)

        attempts = self.max_validation_retries + 1

        last_reasons = []

        for attempt in range(1, attempts + 1):

            candidate = self.gemini_client.generate(prompt)

            is_valid, reasons = self.recommendation_validator.validate(
                candidate
            )

            if is_valid:

                return candidate

            last_reasons = reasons

            logger.warning(
                f"Gemini recommendation failed validation on attempt "
                f"{attempt}/{attempts}: {reasons}"
            )

        raise GeminiUnavailableError(
            f"Gemini recommendation failed validation after "
            f"{attempts} attempt(s): {last_reasons}"
        )

    # =====================================================
    # GENERATE SINGLE RECOMMENDATION
    # =====================================================

    def generate_recommendation(
        self,
        behavior_object,
        risk_object,
        integrity_object,
        operational_entity=None
    ):

        context = self.recommendation_engine.analyze(

            behavior_object,

            risk_object,

            integrity_object,

            operational_entity

        )

        retrieved_knowledge = self.knowledge_retriever.retrieve(context)

        try:

            candidate = self._generate_via_gemini(
                context, retrieved_knowledge
            )

            self.total_generated_by_gemini += 1

        except GeminiUnavailableError as error:

            logger.info(
                f"Using fallback recommendation for entity "
                f"{context.get('entity_id')}: {error}"
            )

            candidate = self._build_fallback_candidate(context)

            self.total_generated_by_fallback += 1

        recommendation_object = self.recommendation_object_builder.build(

            context.get("entity_id"),

            candidate

        )

        return recommendation_object

    # =====================================================
    # GENERATE FOR ONE DATASET
    #
    # Matches Behavior Objects to their Risk and Integrity
    # Objects by entity_id.
    # =====================================================

    def generate_dataset(
        self,
        operational_entities,
        behavior_objects,
        risk_objects,
        integrity_objects
    ):

        risk_by_entity_id = {

            risk_object.get("entity_id"): risk_object

            for risk_object in risk_objects

        }
        operational_by_entity_id = {

            operational_entity.get("entity_id"): operational_entity

            for operational_entity in operational_entities

        }

        integrity_by_entity_id = {

            integrity_object.get("entity_id"): integrity_object

            for integrity_object in integrity_objects

        }

        recommendation_objects = []

        for behavior_object in behavior_objects:

            entity_id = behavior_object.get("entity_id")

            recommendation_objects.append(

                self.generate_recommendation(

                    behavior_object,

                    risk_by_entity_id.get(entity_id, {}),

                    integrity_by_entity_id.get(entity_id, {}),

                    operational_by_entity_id.get(entity_id, {})

                )

            )

        return recommendation_objects

    # =====================================================
    # GENERATE FOR ALL DATASETS
    # =====================================================

    def generate_all(
        self,
        operational_entities_by_dataset,
        behavior_objects_by_dataset,
        risk_objects_by_dataset,
        integrity_objects_by_dataset
    ):

        logger.info("Generating Recommendation Objects...")

        recommendation_objects = {}

        self.total_behaviors = 0
        self.total_recommendations = 0
        self.total_generated_by_gemini = 0
        self.total_generated_by_fallback = 0

        for dataset_name, behaviors in behavior_objects_by_dataset.items():

            logger.info(f"Generating Recommendations : {dataset_name}")

            dataset_recommendations = self.generate_dataset(

                operational_entities_by_dataset.get(dataset_name, []),

                behaviors,

                risk_objects_by_dataset.get(dataset_name, []),

                integrity_objects_by_dataset.get(dataset_name, [])

            )

            recommendation_objects[dataset_name] = dataset_recommendations

            self.total_behaviors += len(behaviors)

            self.total_recommendations += len(dataset_recommendations)

        logger.info(
            f"Behavior Objects Received : {self.total_behaviors}"
        )

        logger.info(
            f"Recommendation Objects Generated : "
            f"{self.total_recommendations}"
        )

        logger.info("Recommendation Agent Completed Successfully.")

        return recommendation_objects

    # =====================================================
    # SUMMARY
    # =====================================================

    def summary(self):

        print("\n")
        print("=" * 70)
        print("RECOMMENDATION AGENT SUMMARY")
        print("=" * 70)

        print(f"Behavior Objects            : {self.total_behaviors}")
        print(f"Recommendation Objects       : {self.total_recommendations}")
        print(f"Generated via Gemini         : {self.total_generated_by_gemini}")
        print(f"Generated via Fallback       : {self.total_generated_by_fallback}")

        print("=" * 70)
