import logging

logger = logging.getLogger(__name__)


class RemediationSelector:
    """
    ==========================================================
    Remediation Selector

    Responsibility:
        Deterministically select the Base Recommendation text
        for an entity — from a similar past incident's playbook,
        a relevant SOP, or a platform best practice already
        retrieved by the Knowledge Retriever, falling back to
        the configured priority-based default text only when
        none of those apply. An LLM is never asked to author
        this text; the Multi-LLM Selection Agent may only reword
        or enhance it afterward.

        This candidate is always built first, before any LLM is
        invoked, and is used verbatim as the final recommendation
        whenever every configured LLM is unavailable — the
        Recommendation Agent never fails to produce a
        recommendation.

    Input:
        Recommendation Context Dictionary, Retrieved Knowledge
        Dictionary

    Output:
        Base Recommendation Candidate Dictionary:
            priority, category, base_recommendation,
            knowledge_source, reason, expected_impact,
            estimated_recovery_time, confidence,
            automation_possible, human_approval_required

    DOES NOT
    --------
    - Calculate priority, category, or impact estimates (the
      Priority Calculator / Impact Estimator already did that;
      this module only consumes their output from the context)
    - Retrieve knowledge (that is the Knowledge Retriever's job)
    - Call any LLM
    - Validate or build the final Recommendation Object
    ==========================================================
    """

    # =====================================================
    # INITIALIZATION
    # =====================================================

    def __init__(self, rule_engine):

        self.rule_engine = rule_engine

        logger.info("Remediation Selector Ready.")

    # =====================================================
    # SELECT BASE RECOMMENDATION TEXT
    #
    # Preference order: similar past incident playbook -> SOP
    # -> platform best practice -> priority-based default text.
    # =====================================================

    def _select_base_text(self, context, retrieved_knowledge):

        similar_incident = retrieved_knowledge.get("similar_incident")

        if similar_incident:

            return similar_incident, "similar_incident_playbook"

        relevant_sop = retrieved_knowledge.get("relevant_sop")

        if relevant_sop:

            return relevant_sop, "sop_library"

        platform_best_practice = retrieved_knowledge.get(
            "platform_best_practice"
        )

        if platform_best_practice:

            return platform_best_practice, "platform_best_practice"

        fallback_config = self.rule_engine.get_fallback_config()

        recommendation_by_priority = fallback_config.get(
            "recommendation_by_priority", {}
        )

        priority = context.get("priority")

        default_text = (
            "Review this entity; no specific fallback recommendation "
            "configured for this priority."
        )

        return (
            recommendation_by_priority.get(priority, default_text),
            "priority_default"
        )

    # =====================================================
    # SELECT
    # =====================================================

    def select(self, context, retrieved_knowledge):

        fallback_config = self.rule_engine.get_fallback_config()

        base_recommendation, knowledge_source = self._select_base_text(
            context, retrieved_knowledge
        )

        return {

            "priority": context.get("priority"),

            "category": context.get("category"),

            "base_recommendation": base_recommendation,

            "knowledge_source": knowledge_source,

            "reason": fallback_config.get(
                "reason",
                "Generated by the deterministic Recommendation Engine "
                "from operational knowledge."
            ),

            "expected_impact": context.get("expected_impact"),

            "estimated_recovery_time": context.get(
                "estimated_recovery_time"
            ),

            "confidence": fallback_config.get("confidence", 0.3),

            "automation_possible": context.get("automation_possible"),

            "human_approval_required": context.get(
                "human_approval_required"
            )

        }
