import pytest

from agents.multi_llm_selection.llm_response_parser import (
    LLMResponseParser,
    LLMResponseValidationError
)
from agents.multi_llm_selection.multi_llm_selection_agent import (
    MultiLLMSelectionAgent
)
from agents.multi_llm_selection.gemini_client import GeminiProviderError
from agents.multi_llm_selection.grok_client import GrokProviderError
from agents.multi_llm_selection.ollama_client import OllamaProviderError


# ==========================================================
# Fixtures
# ==========================================================

@pytest.fixture
def valid_llm_response():

    return {

        "priority": "HIGH",

        "recommendation": "Restart the ingestion job and re-validate schema.",

        "reason": "Integrity failure combined with elevated risk severity.",

        "expected_impact": "Significant — degraded reliability without action.",

        "estimated_recovery_time": "Short-term (30 minutes - 4 hours)",

        "automation_possible": False,

        "human_approval_required": True,

        "confidence": 0.82,

        "generated_by": "gemini",

    }


@pytest.fixture
def rule_recommendation():

    return {

        "priority": "HIGH",

        "recommendation": "Investigate this entity's recent deviation.",

        "reason": "Generated by the deterministic fallback path.",

        "expected_impact": "Significant — degraded reliability without action.",

        "estimated_recovery_time": "Short-term (30 minutes - 4 hours)",

        "confidence": 0.3,

        "automation_possible": False,

        "human_approval_required": True,

    }


# ==========================================================
# LLM Response Parser
# ==========================================================

class TestLLMResponseParser:

    def test_valid_response_is_normalized(self, valid_llm_response):

        parser = LLMResponseParser()

        result = parser.parse(valid_llm_response, expected_priority="HIGH")

        assert result["priority"] == "HIGH"
        assert result["automation_possible"] is False
        assert result["confidence"] == 0.82

    def test_missing_field_is_rejected(self, valid_llm_response):

        parser = LLMResponseParser()

        broken = dict(valid_llm_response)

        del broken["reason"]

        with pytest.raises(LLMResponseValidationError):

            parser.parse(broken)

    def test_invalid_priority_is_rejected(self, valid_llm_response):

        parser = LLMResponseParser()

        broken = dict(valid_llm_response)

        broken["priority"] = "URGENT"

        with pytest.raises(LLMResponseValidationError):

            parser.parse(broken)

    def test_priority_conflict_is_rejected(self, valid_llm_response):

        parser = LLMResponseParser()

        conflicting = dict(valid_llm_response)

        conflicting["priority"] = "LOW"

        with pytest.raises(LLMResponseValidationError):

            parser.parse(conflicting, expected_priority="HIGH")

    def test_string_boolean_is_coerced(self, valid_llm_response):

        parser = LLMResponseParser()

        stringified = dict(valid_llm_response)

        stringified["automation_possible"] = "true"

        result = parser.parse(stringified)

        assert result["automation_possible"] is True

    def test_invalid_boolean_is_rejected(self, valid_llm_response):

        parser = LLMResponseParser()

        broken = dict(valid_llm_response)

        broken["automation_possible"] = "maybe"

        with pytest.raises(LLMResponseValidationError):

            parser.parse(broken)

    def test_confidence_out_of_range_is_rejected(self, valid_llm_response):

        parser = LLMResponseParser()

        broken = dict(valid_llm_response)

        broken["confidence"] = 1.5

        with pytest.raises(LLMResponseValidationError):

            parser.parse(broken)

    def test_non_dict_response_is_rejected(self):

        parser = LLMResponseParser()

        with pytest.raises(LLMResponseValidationError):

            parser.parse("not a dictionary")


# ==========================================================
# Multi-LLM Selection Agent
#
# Provider clients are monkeypatched so these tests never make
# a real network call.
# ==========================================================

class TestMultiLLMSelectionAgent:

    def _agent_with_fakes(self, monkeypatch, gemini_result=None,
                           grok_result=None, ollama_result=None):

        agent = MultiLLMSelectionAgent()

        def make_fake(result_or_error):

            def fake_generate(prompt):

                if isinstance(result_or_error, Exception):

                    raise result_or_error

                return result_or_error

            return fake_generate

        if gemini_result is not None:

            monkeypatch.setattr(
                agent.provider_clients["gemini"],
                "generate",
                make_fake(gemini_result)
            )

        if grok_result is not None:

            monkeypatch.setattr(
                agent.provider_clients["grok"],
                "generate",
                make_fake(grok_result)
            )

        if ollama_result is not None:

            monkeypatch.setattr(
                agent.provider_clients["ollama"],
                "generate",
                make_fake(ollama_result)
            )

        return agent

    def test_low_priority_never_calls_any_provider(
        self, monkeypatch, rule_recommendation
    ):

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=GeminiProviderError("should not be called"),
        )

        result = agent.select(
            "prompt", rule_recommendation, "LOW", entity_id="e1"
        )

        assert result["recommendation_source"] == "deterministic"
        assert result["selected_model"] is None
        assert result["recommendation"] == rule_recommendation["recommendation"]

    def test_medium_priority_never_calls_any_provider(
        self, monkeypatch, rule_recommendation
    ):

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=GeminiProviderError("should not be called"),
        )

        result = agent.select(
            "prompt", rule_recommendation, "MEDIUM", entity_id="e2"
        )

        assert result["recommendation_source"] == "deterministic"
        assert result["selected_model"] is None

    def test_critical_priority_uses_ollama_and_bypasses_gemini(
        self, monkeypatch, rule_recommendation, valid_llm_response
    ):

        # Even if Gemini and Grok are mock-configured to be successful, they must be bypassed
        # and Ollama must be used since we are in the demo configuration.
        response = dict(valid_llm_response)
        response["generated_by"] = "ollama"

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=valid_llm_response,
            grok_result=valid_llm_response,
            ollama_result=response
        )

        result = agent.select(
            "prompt", rule_recommendation, "CRITICAL", entity_id="e3"
        )

        assert result["recommendation_source"] == "llm"
        assert result["selected_model"] == "ollama"

    def test_bypasses_grok_and_uses_ollama(
        self, monkeypatch, rule_recommendation, valid_llm_response
    ):

        response = dict(valid_llm_response)
        response["generated_by"] = "ollama"

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=GeminiProviderError("quota exceeded"),
            grok_result=valid_llm_response,
            ollama_result=response,
        )

        result = agent.select(
            "prompt", rule_recommendation, "HIGH", entity_id="e4"
        )

        assert result["recommendation_source"] == "llm"
        assert result["selected_model"] == "ollama"

    def test_falls_through_to_ollama(
        self, monkeypatch, rule_recommendation, valid_llm_response
    ):

        response = dict(valid_llm_response)
        response["generated_by"] = "ollama"

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=GeminiProviderError("unavailable"),
            grok_result=GrokProviderError("unavailable"),
            ollama_result=response,
        )

        result = agent.select(
            "prompt", rule_recommendation, "HIGH", entity_id="e5"
        )

        assert result["recommendation_source"] == "llm"
        assert result["selected_model"] == "ollama"

    def test_all_providers_failing_returns_deterministic(
        self, monkeypatch, rule_recommendation
    ):

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=GeminiProviderError("unavailable"),
            grok_result=GrokProviderError("unavailable"),
            ollama_result=OllamaProviderError("unavailable"),
        )

        result = agent.select(
            "prompt", rule_recommendation, "CRITICAL", entity_id="e6"
        )

        assert result["recommendation_source"] == "deterministic"
        assert result["selected_model"] is None
        assert result["recommendation"] == rule_recommendation["recommendation"]

    def test_invalid_ollama_response_falls_to_deterministic(
        self, monkeypatch, rule_recommendation, valid_llm_response
    ):

        malformed = dict(valid_llm_response)

        del malformed["reason"]

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=valid_llm_response,
            grok_result=valid_llm_response,
            ollama_result=malformed,
        )

        result = agent.select(
            "prompt", rule_recommendation, "HIGH", entity_id="e7"
        )

        assert result["recommendation_source"] == "deterministic"
        assert result["selected_model"] is None

    def test_unexpected_exception_never_propagates(
        self, monkeypatch, rule_recommendation
    ):

        agent = self._agent_with_fakes(
            monkeypatch,
            gemini_result=RuntimeError("totally unexpected"),
            grok_result=RuntimeError("also unexpected"),
            ollama_result=RuntimeError("still unexpected"),
        )

        result = agent.select(
            "prompt", rule_recommendation, "CRITICAL", entity_id="e8"
        )

        assert result["recommendation_source"] == "deterministic"
        assert result["selected_model"] is None


class TestOllamaClientJsonRepair:

    def test_parse_valid_json(self):
        from agents.multi_llm_selection.ollama_client import OllamaClient
        from agents.multi_llm_selection.llm_config import LLMConfig
        config = LLMConfig()
        client = OllamaClient(config)
        raw = '{"priority": "HIGH", "recommendation": "Restart"}'
        result = client._parse_response(raw)
        assert result["priority"] == "HIGH"
        assert result["recommendation"] == "Restart"

    def test_parse_json_with_markdown_fences_and_text(self):
        from agents.multi_llm_selection.ollama_client import OllamaClient
        from agents.multi_llm_selection.llm_config import LLMConfig
        config = LLMConfig()
        client = OllamaClient(config)
        raw = "Here is the response:\n```json\n{\n  \"priority\": \"HIGH\",\n  \"recommendation\": \"Restart\"\n}\n```\nHope this helps!"
        result = client._parse_response(raw)
        assert result["priority"] == "HIGH"

    def test_parse_python_dict_literal(self):
        from agents.multi_llm_selection.ollama_client import OllamaClient
        from agents.multi_llm_selection.llm_config import LLMConfig
        config = LLMConfig()
        client = OllamaClient(config)
        raw = "{'priority': 'HIGH', 'recommendation': 'Restart', 'automation_possible': True, 'confidence': 0.8,}"
        result = client._parse_response(raw)
        assert result["priority"] == "HIGH"
        assert result["automation_possible"] is True
        assert result["confidence"] == 0.8

    def test_parse_json_with_trailing_comma(self):
        from agents.multi_llm_selection.ollama_client import OllamaClient
        from agents.multi_llm_selection.llm_config import LLMConfig
        config = LLMConfig()
        client = OllamaClient(config)
        raw = '{"priority": "HIGH", "recommendation": "Restart",}'
        result = client._parse_response(raw)
        assert result["priority"] == "HIGH"
